/* 낱말 표 — 화면에 뜨는 주제 낱말은 전부 여기 한 곳에서 온다.

   앞선 저장소(atelier → pkm-atelier)에서 배운 것이다. 규칙 코드는 한 줄도 안
   고쳐도 도는데, 사람이 읽는 말이 화면 코드에 박혀 있으면 주제를 바꿀 때
   "모함 건업" 같은 것이 뜬다. 그래서 화면은 W('card.cost') 로 부르고,
   주제를 바꾸면 이 파일 하나만 갈아 끼운다.

   쓰는 법
     W('card.cost')                → '값'
     W('art.count', {n: 3})        → 자리표시자가 있으면 채워 넣는다
     W('없는.열쇠')                 → 열쇠를 그대로 돌려주고 콘솔에 적는다
                                      (조용히 빈칸이 되는 것보다 낫다)

   자료의 말(신화권·무기 종류·기술 이름)은 여기 없다. 그것은 data/group.json 과
   data/skill.json 이 준다 — 카드가 늘면 자료가 늘지 화면 낱말이 늘지 않는다. */
(function (root) {
  'use strict';

  var WORDS = {
    /* 저장소 이름표 */
    'app.title': '신화 무기 공방',
    'app.subtitle': '신화 속 무기를 사람으로 그리고, 판에 놓아 자동으로 싸운다.',
    'app.code': 'MYTH / 001',
    'app.brand': 'MYTHIC ARMS × ATELIER',   /* 큰 제목 위 작은 글씨. 저장소 이름이 아니라 만든 이의 표다 */
    'workspace.signature': 'ARMORY OF LEGENDS',

    /* 항해 — 네 화면 */
    'nav.index': '공방',
    'nav.dex': '도감',
    'nav.auto': '오토 배틀',
    'nav.run': '던전',
    'nav.draft': '드래프트',
    'nav.duel': '결투',
    'nav.prompt': '프롬프트',

    /* 집 화면 */
    'home.title': '무기가 사람이 되어 싸운다.',
    'home.intro': '묠니르·아이기스·여의봉·바즈라. 신화 속 무기를 의인화한 카드로 상점에서 사고 판에 놓으면 싸움은 저절로 돈다. 사람이 하는 일은 무엇을 사고 어디에 두느냐뿐이다.',
    'home.tag': '북유럽 · 그리스 · 한국 · 중국 · 일본 · 인도 · 이집트 · 서아시아 · 켈트 · 아메리카 · 기사 전설의 신화 무기',
    'home.dex.code': '01 / CODEX',
    'home.dex.title': '신기 도감',
    'home.dex.note': '모든 무기의 값·체력·공격·기술과 원래 주인. 그림이 올라오면 여기 걸린다.',
    'home.auto.code': '02 / AUTO BATTLE',
    'home.auto.title': '오토 배틀러',
    'home.auto.note': '금으로 사고, 앞줄·뒷줄에 놓고, 같은 자루 셋을 모아 별을 올린다. 싸움은 자동이다.',
    'home.run.code': '03 / DUNGEON',
    'home.run.title': '던전',
    'home.run.note': '무기 셋을 데려가 아홉 칸의 길을 간다. 각성은 카드를 쌓아 열고, 저주는 감수한다. 이기면 카드, 상점에서 덱을 다듬는다.',
    'home.draft.code': '04 / DRAFT',
    'home.draft.title': '신기 드래프트',
    'home.draft.note': '우리 근본. 세 편이 팩에서 무기 여섯과 주인 여섯을 집어 짝을 짓는다. 결속과 인연이 승부를 가른다.',
    'home.duel.code': '05 / DUEL',
    'home.duel.title': '신기 결투',
    'home.duel.note': '덱 스물다섯, 손패 열. 세 줄에 내려 힘을 겨루고 세 판 중 둘을 따낸다. 열한 주인을 이기며 각성판·저주판·날씨판을 모은다.',
    'home.prompt.code': '06 / STUDIO',
    'home.prompt.title': '그림 프롬프트',
    'home.prompt.note': '무기당 액션 한 장. 화풍을 고르고 문장을 받아 그림 모델에 넣는다.',
    'home.themes': '아홉 신전',
    'home.themes.note': '신화권마다 두 곳, 그리고 모두가 모이는 만신전. 어느 화면이든 같이 바뀐다.',
    'home.hall': '신전 홀',
    'home.hall.note': '올라온 무기가 제단을 돈다',
    'home.hall.note.awaken': '권능이 깨어난다 — 3성의 모습',
    'home.hall.note.cursed': '전설의 어두운 면이 드러난다',
    'home.hall.modes': '상태 보기',
    'home.hall.awaken': '각성',
    'home.hall.cursed': '저주',
    'home.hall.pick': '{temple}에 모실 무기는 도감에서 고른다',
    'home.hall.picked': '{temple}에 모신 무기 — 도감에서 바꾼다',
    'home.patch': '패치 기록',
    'home.patch.open': '패치 기록 보기',
    'home.patch.close': '닫기',
    'home.patch.note': '두 세션이 무엇을 왜 고쳤나. 새 것이 위.',
    'home.patch.loading': '읽는 중',
    'home.patch.none': '아직 적힌 것이 없다',
    'home.patch.fail': '패치 기록을 읽지 못했다 — docs/PATCH.md',

    /* 겉모습 */
    'ui.theme': '테마',
    'ui.density': '화면 밀도',
    'ui.density.compact': '촘촘하게',
    'ui.density.relaxed': '여유롭게',
    'ui.header.fold': '머리 접기 — 제목을 숨긴다',
    'ui.header.fold.short': '머리 접기',
    'ui.settings': '설정 — 테마·화면 밀도',
    'ui.help.short': '설명 보기',
    'ui.help.short.on': '설명 숨기기',
    'ui.header.unfold': '머리 펼치기',
    'ui.help.show': '설명 보기 — 화면마다 붙은 안내 글을 펼친다',
    'ui.help.hide': '설명 숨기기',
    'ui.loading': '읽는 중…',
    'ui.error': '자료를 못 읽었다 — {message}',
    'ui.back': '목록으로',
    /* 신전 — 신화권마다 하나둘씩과 만신전. 열쇠는 옛 이름 그대로다 (저장된 선호가 살아야 하니) */
    'theme.midnight': '발할라의 밤', 'theme.moss': '세계수 그늘',
    'theme.daylight': '대리석 신전', 'theme.deep': '심해 신전',
    'theme.blossom': '벚꽃 사당', 'theme.ember': '주홍 사당',
    'theme.sand': '태양 사원', 'theme.plum': '연꽃 사원의 밤',
    'theme.stone': '안개의 선돌', 'theme.dancheong': '단청 전각', 'theme.nile': '나일 열주', 'theme.lapis': '청금석 성문',
    'theme.pantheon': '만신전',
    'theme.myth.midnight': '북유럽 · 밤', 'theme.myth.moss': '북유럽 · 그늘',
    'theme.myth.daylight': '그리스 · 낮', 'theme.myth.deep': '그리스 · 바다',
    'theme.myth.blossom': '일본 · 봄', 'theme.myth.ember': '중국 · 밤',
    'theme.myth.sand': '인도 · 낮', 'theme.myth.plum': '인도 · 밤',
    'theme.myth.stone': '켈트 · 안개', 'theme.myth.dancheong': '한국 · 달밤', 'theme.myth.nile': '이집트 · 황혼', 'theme.myth.lapis': '서아시아 · 황혼',
    'theme.myth.pantheon': '모든 신화 · 밤',
    'theme.note.midnight': '먹구름 위 금 — 번개 치는 하늘의 궁전',
    'theme.note.moss': '겨우살이 걸린 물푸레나무 그늘',
    'theme.note.daylight': '흰 대리석 기둥과 에게해 빛',
    'theme.note.deep': '삼지창이 잠든 바닷속 회랑',
    'theme.note.blossom': '주홍 문에 흩날리는 벚꽃',
    'theme.note.ember': '옻칠한 어둠과 등롱 불',
    'theme.note.sand': '사프란 빛 계단과 태양 원반',
    'theme.note.plum': '남색 밤하늘 아래 연꽃 연못',
    'theme.note.stone': '안개 낀 언덕의 선돌과 삼중 나선',
    'theme.note.dancheong': '달빛 아래 단청 공포와 연등',
    'theme.note.nile': '해 진 강가의 파피루스 기둥과 날개 달린 해',
    'theme.note.lapis': '청금석 벽돌의 금 사자와 저녁 지구라트',
    'theme.note.pantheon': '흑요석과 금 — 모든 무기가 한자리에',

    /* 던전 */
    'run.title': '던전',
    'run.subtitle': '무기 셋을 데려가 아홉 칸의 길을 간다. 각성은 쌓아서 열고, 저주는 감수한다.',
    'run.saved': '길은 이 브라우저에 남는다.',
    'run.pick.title': '동료를 고른다',
    'run.pick.note': '셋. 그림이 있는 무기가 먼저 온다. 종류가 다르면 카드가 고르게 섞인다.',
    'run.pick.count': '{n} / 3',
    'run.pick.start': '길을 나선다',
    'run.sortie.title': '출정 — 드래프트에서 온 짝',
    'run.sortie.note': '여섯 중 셋을 데려간다. 나머지 셋은 예비 — 동료가 쓰러지면 다음 칸에서 올라온다. 상대는 드래프트의 적 편.',
    'run.sortie.rank': '드래프트 {rank}등 — 상대 체력 ×{k}',
    'run.sortie.plain': '드래프트 없이 고른다',
    'run.pair.own': '전용 — 게이지 셋',
    'run.pair.favor': '손에 익은 무기 +10%',
    'run.pair.feud': '악연 — 저주를 거절할 수 없다',
    'run.reserve': '예비 {n}',
    'run.log.reserve': '{a} 이(가) {b} 의 자리에 올라온다',
    'run.ask.feud': '악연이 붙어 있다 — 거절할 수 없다.',
    'run.node.fight': '싸움', 'run.node.boss': '보스', 'run.node.shrine': '제단', 'run.node.gate': '저주의 문', 'run.node.rest': '휴식', 'run.node.shop': '상점',
    'run.map.title': '길',
    'run.map.note': '아홉 칸. 싸움 넷, 제단·저주의 문·상점·휴식, 끝에 보스.',
    'run.map.go': '나아간다',
    'run.party': '동료',
    'run.enemy': '상대',
    'run.hp': '{hp} / {max}',
    'run.state.base': '기본', 'run.state.awaken': '각성', 'run.state.cursed': '저주',
    'run.gauge': '각성 {n} / {max}',
    'run.figure.dead': '쓰러짐',
    'run.battle.turn': '{n}턴',
    'run.battle.mana': '마나',
    'run.battle.deck': '덱 {n} · 버림 {m}',
    'run.battle.end': '턴 끝',
    'run.battle.hand': '손패 — 카드를 누르면 낸다. 상대가 여럿이면 상대를 골라 준다. 상대 위의 표시가 다음 턴에 할 일이다.',
    'run.battle.target': '{name} — 누구를 치나',
    'run.battle.boss': '보스',
    'run.intent.hit': '{b} 에게 {d}',
    'run.intent.all': '전부 {d}',
    'run.intent.stun': '기절 — 쉰다',
    'run.intent.title': '다음 행동',
    'run.incoming': '받을 피해 {d}',
    'run.incoming.taunt': '도발 — 한 대 공격을 다 받는다',
    'run.card.unique': '고유',
    'run.ask.title': '{name} — 저주를 받아들일까',
    'run.ask.text': '공격이 세지고 모습이 바뀐다. 대신 카드를 낼 때마다 피 1을 잃고, 회복과 보호막을 못 받는다. 영구다.',
    'run.ask.yes': '받아들인다',
    'run.ask.no': '버틴다',
    'run.result.win': '이겼다',
    'run.result.note': '저주받지 않은 동료가 피 15%를 되찾는다.',
    'run.purse': '금화 {g} · 덱 {n}장',
    'run.loot.gold': '금화 +{n}',
    'run.loot.title': '전리품',
    'run.loot.note': '한 장을 골라 덱에 넣는다. 안 골라도 된다. 카드는 그 무기의 것 — 무기가 쓰러지면 같이 빠진다.',
    'run.loot.taken': '덱에 넣었다',
    'run.loot.skip': '고르지 않고 간다',
    'run.card.rare': '희귀',
    'run.shop.title': '상점',
    'run.shop.note': '싸움에서 번 금화를 쓴다. 카드는 사는 만큼, 빼기·치유·정화는 한 번씩.',
    'run.shop.cards': '카드',
    'run.shop.price': '{n} 금화',
    'run.shop.sold': '샀다',
    'run.shop.care': '손보기',
    'run.shop.remove': '카드 한 장 빼기 · {n} 금화',
    'run.shop.remove.note': '뺄 카드를 누른다. 무기마다 한 장은 남는다.',
    'run.shop.remove.cancel': '그만둔다',
    'run.shop.heal': '치유 — 동료 피 {p}% · {n} 금화',
    'run.shop.purify': '정화 — {name} 의 저주를 푼다 · {n} 금화',
    'run.shop.purify.none': '정화 — 저주받은 동료가 없다',
    'run.shop.done': '했다',
    'run.shop.leave': '떠난다',
    'run.result.next': '다음 칸',
    'run.shrine.title': '제단',
    'run.shrine.note': '동료 하나가 영구히 깨어난다. 모든 싸움을 각성으로 시작한다.',
    'run.shrine.pick': '깨운다',
    'run.shrine.none': '깨울 동료가 없다',
    'run.pass': '지나간다',
    'run.gate.title': '저주의 문',
    'run.gate.note': '동료 하나가 저주를 받는다. 세지지만 피를 잃고 회복을 못 받는다. 안 받아도 된다.',
    'run.gate.pick': '저주를 받는다',
    'run.rest.title': '휴식',
    'run.rest.note': '저주받지 않은 동료가 피 30%를 되찾는다.',
    'run.rest.go': '쉰다',
    'run.won.title': '길의 끝',
    'run.won.note': '보스를 쓰러뜨렸다. 각성 {a} · 저주 {c}.',
    'run.lost.title': '쓰러졌다',
    'run.lost.note': '{n}번째 칸에서. 각성 {a} · 저주 {c}.',
    'run.again': '새 길',
    'run.abandon': '길을 버린다',
    'run.log.start': '{n} 나타났다',
    'run.log.play': '{a}: {name}',
    'run.log.hit': '{a} → {b} {d}',
    'run.log.down': '{b} 쓰러짐',
    'run.log.ehit': '{a} → {b} {d}',
    'run.log.eskill': '{a} 기술 → {b} {d}',
    'run.log.awaken': '{a} 각성!',
    'run.log.curse': '{a} 저주를 받았다',
    'run.log.fall': '{b} 쓰러졌다',
    'run.log.heal': '{b} +{d}',
    'run.log.shield': '{b} 보호막 {d}',
    'run.log.stun': '{b} 기절',
    'run.log.taunt': '{a} 도발 — 한 대 공격을 대신 받는다',
    'run.log.skip': '{a} 못 움직인다',
    'run.log.bleed': '{a} 피 -1',
    'run.log.win': '이겼다',
    'run.log.lose': '졌다',
    'run.log.ask': '{a} 피가 낮다',
    'run.log.shrine': '{a} 영구 각성',
    'run.log.gate': '{a} 저주',
    'run.log.rest': '쉬었다',
    'run.log.gold': '금화 +{d}',
    'run.log.take': '{a}: {name} → 덱',
    'run.log.buy': '{a}: {name} 샀다 (-{d})',
    'run.log.remove': '{a}: {name} 뺐다 (-{d})',
    'run.log.shopheal': '치유했다 (-{d})',
    'run.log.purify': '{a} 정화 — 저주가 풀렸다 (-{d})',

    /* 드래프트 */
    'draft.title': '신기 드래프트',
    'draft.subtitle': '세 편이 열두 라운드에 무기 여섯과 주인 여섯을 집어 짝을 짓는다. 결속과 인연이 승부를 가른다.',
    'draft.setup.title': '판을 짠다',
    'draft.setup.note': '팩 아홉 장에서 한 장. 안 집은 것은 버림패로 돌아가 다시 섞인다.',
    'draft.lv': '적장',
    'draft.lv.0': '신참', 'draft.lv.1': '숙련', 'draft.lv.2': '에이스',
    'draft.lv.note': '신참은 가끔 헛발질하고 인연을 못 본다. 숙련은 전용 인연을 본다. 에이스는 다 보고 한 장이면 터질 인연을 내다본다.',
    'draft.rr': '보급',
    'draft.rr.n': '{n}번',
    'draft.rr.note': '팩이 시원치 않으면 물린다. 마지막 라운드엔 못 쓴다.',
    'draft.myths': '이번 판의 신화권',
    'draft.myths.note': '고른 권의 무기와 주인만 팩에 나온다 — {min}~{max}권, 또는 {all}권 전부. 적을수록 같은 권의 결속과 인연이 잘 모이고, 많을수록 판이 넓다.',
    'draft.myths.random': '무작위 셋',
    'draft.myths.all': '전부',
    'draft.start': '드래프트 시작',
    'draft.round': '{n} / {total} 라운드',
    'draft.type.weapon': '무기', 'draft.type.wielder': '주인',
    'draft.pack.weapon': '무기를 집는다', 'draft.pack.wielder': '주인을 집는다',
    'draft.pack.note': '카드를 누르면 미리보기, 다시 누르면 집는다.',
    'draft.pick': '집는다',
    'draft.resupply': '보급 요청',
    'draft.resupply.left': '남은 보급 {n}',
    'draft.waiting': '적장이 두는 중',
    'draft.seat.0': '아군', 'draft.seat.1': '적 1', 'draft.seat.2': '적 2',
    'draft.team.title': '내 편성',
    'draft.team.pairs': '짝 {n}',
    'draft.team.empty': '아직 비었다',
    'draft.unpaired': '짝 없음',
    'draft.preview': '집으면 {delta}',
    'draft.score.total': '합계',
    'draft.score.pairs': '출격 {n}짝',
    'draft.score.solo': '미편성 {n}',
    'draft.score.syn.myth': '결속 · {key} {n}',
    'draft.score.syn.kind': '결속 · {key} {n}',
    'draft.score.pledge': '연대 · {name}',
    'draft.score.feud': '악연 · {name}',
    'draft.fired': '인연이 맺어졌다 — {list}',
    'draft.log.title': '지명 기록',
    'draft.log.rr': '보급 요청',
    'draft.result.title': '결과',
    'draft.result.rank': '{rank}등',
    'draft.result.gap': '1등과 3등 차이 {n}',
    'draft.result.mvp': '최고의 짝',
    'draft.again': '새 판',
    'draft.sortie': '출정 — 던전으로',
    'draft.sortie.note': '내 짝 여섯 중 셋을 데려가고 나머지는 예비다. 상대는 적 두 편의 짝, 보스는 1등의 최고의 짝.',
    'draft.abandon': '판을 버린다',
    'draft.records': '전적',
    'draft.records.line': '{games}판 · 1등 {first} · 2등 {second} · 3등 {third} · 최고 {best}',
    'draft.records.erase': '전적 지우기',
    'draft.saved': '판은 이 브라우저에 남는다.',
    'draft.stat.weapon': '힘 {n}',
    'draft.stat.wielder': '힘 {n} · {myth}',
    'draft.sync': '궁합 ×{n}',
    'draft.owner': '원래 주인 {name}',
    'draft.favor': '손에 익은 {kind}',

    /* 새 판 알림 */
    'fresh.notice': '새 판이 나왔습니다. 하던 것을 마치고 눌러 주세요.',
    'fresh.reload': '갈아타기',
    'fresh.close': '닫기',
    'fresh.stamp': '판',

    /* 카드 값 — 자료 이름은 data/ 가 준다. 여기는 칸 이름뿐이다 */
    'kind.card': '무기',
    'card.myth': '신화권',
    'card.kind': '종류',
    'card.cost': '값',
    'card.cost.n': '{n}금',
    'card.hp': '체력',
    'card.atk': '공격',
    'card.spd': '공격 간격',
    'card.spd.n': '{n}박',
    'card.range': '사거리',
    'card.skill': '기술',
    'card.wielder': '원래 주인',
    'card.text': '전설',
    'card.star': '{n}성',
    'card.curse': '저주',
    'card.curse.n': '체력 {at}%부터 — 공격 +{atk}% · 기술 +{skill}% · 박자당 {bleed}%',
    'card.curse.note': '한 판에 한 번 발현. 세지는 대신 피를 잃고 치유·보호막을 못 받는다. 되살아나도 안 풀린다.',
    'card.stats': '세기',
    'range.melee': '근접 — 앞줄만 친다',
    'range.reach': '중거리 — 앞줄과 그 뒤까지',
    'range.ranged': '원거리 — 아무 줄이나',
    'range.short.melee': '근접',
    'range.short.reach': '중거리',
    'range.short.ranged': '원거리',

    /* 도감 */
    'dex.title': '신기 도감',
    'dex.filter.title': '거르기',
    'museum.open': '박물관',
    'museum.open.note': '전시실을 걸어 다니며 본다',
    'museum.back': '도감 목록',
    'museum.hall': '신화 무기 박물관',
    'museum.lobby': '중앙 홀',
    'museum.rooms': '전시실 바로 가기',
    'museum.room': '{name}관',
    'museum.mode.base': '기본',
    'museum.mode.awaken': '각성',
    'museum.mode.cursed': '저주',
    'museum.help.pc': 'WASD·방향키로 걷고 Q·E 로 돈다. 끌어서 둘러보고, 액자를 누르면 자세히, 두 번 누르면 그 앞으로',
    'museum.help.touch': '왼쪽 아래 손잡이로 걷고, 화면을 끌어서 둘러본다. 액자를 누르면 자세히, 두 번 누르면 그 앞으로',
    'museum.pending': '준비 중',
    'museum.broken': '그림을 못 불러왔다',
    'museum.more': '자세히',
    'museum.dex': '도감에서 보기',
    'museum.close': '닫기',
    'museum.canvas': '박물관 전시실 — 걸어 다니며 본다',
    'museum.nogl': '이 브라우저는 3D 를 그리지 못한다.',
    'museum.tinted.awaken': '아직 각성 그림이 없어 기본 그림을 금빛으로 비춘다',
    'museum.tinted.cursed': '아직 저주 그림이 없어 기본 그림을 핏빛으로 비춘다',
    'dex.filter.search': '이름·주인·스킨으로 찾기',
    'dex.filter.reset': '조건 초기화',
    'dex.filter.all': '전체',
    'dex.filter.myth': '신화권',
    'dex.filter.kind': '종류',
    'dex.filter.cost': '값',
    'dex.filter.style': '화풍',
    'dex.filter.art': '그림',
    'dex.filter.art.any': '있든 없든',
    'dex.filter.art.yes': '그림 있는 것',
    'dex.filter.art.no': '아직 없는 것',
    'dex.filter.skin': '스킨',
    'dex.filter.skin.any': '있든 없든',
    'dex.filter.skin.yes': '스킨 있는 것',
    'dex.filter.skin.art': '스킨 그림까지 있는 것',
    'dex.filter.count': '{cards}자루 · 그림 {images}장',
    'dex.filter.empty': '조건에 맞는 무기가 없다',
    'dex.view.small': '촘촘히',
    'dex.view.normal': '보통',
    'dex.style': '화풍',
    'dex.style.unknown': '화풍 미상',
    'dex.style.compare': '화풍 나란히',
    'dex.cut.portrait': '액션',
    'dex.cut.awaken': '각성',
    'dex.cut.cursed': '저주',
    'dex.cursed.note': '저주가 발현되면 이 그림으로 바뀐다',
    'dex.cut.casual': '일상컷',
    'dex.cut.extra': '특별컷',
    'dex.extra': '특별컷',
    'dex.extra.note': '저주형처럼 놀이에 안 쓰는 변주. 파일 이름 _f_extraN',
    'dex.cut.number': '{cut} {n}',
    'dex.casual': '일상컷',
    'dex.skin': '스킨',
    'dex.hall': '신전',
    'dex.hall.add': '{temple}에 모신다',
    'dex.hall.remove': '{temple}에서 내린다',
    'dex.hall.full': '{temple}이 찼다 — {max}자리',
    'dex.hall.count': '{temple} {n} / {max}',
    'dex.hall.clear': '{temple} 비우기',
    'dex.hall.on': '모심',
    'dex.hall.note': '메인 화면의 신전에 도는 무기 — 지금 테마의 신전 몫이다. 비워 두면 그 신전의 신화권에서 매번 무작위로 고른다.',
    'dex.cut.skin': '스킨 · {name}',
    'dex.skin.note': '치장이다. 수치는 그대로다. 스킨의 각성·저주 그림이 없으면 판에서 효과로 덮인다.',
    'dex.skin.use': '판에서 이 스킨으로',
    'dex.skin.using': '판에서 쓰는 중 · 되돌리기',
    'dex.skin.on': '스킨 착용',
    'dex.awaken.note': '3성이 되면 이 그림으로 바뀐다',
    'dex.selected': '고른 것',
    'dex.zoom': '크게 보기',
    'dex.zoom.close': '닫기',
    'dex.zoom.prev': '앞 컷',
    'dex.zoom.next': '다음 컷',
    'dex.zoom.original': '원본 열기',
    'dex.synergy': '시너지',

    /* 오토 배틀 */
    'auto.title': '오토 배틀러',
    'auto.round': '{n}라운드',
    'auto.round.pve': '수호자',
    'auto.round.pvp': '맞대결',
    'auto.alive': '생존 {n} / {total}',
    'auto.level': '레벨',
    'auto.level.xp': '{xp} / {need}',
    'auto.level.max': '최대',
    'auto.xp.buy': '레벨 업 {n}금',
    'auto.xp.note': '경험치 +{n}. 레벨이 곧 판에 올릴 수 있는 수이고, 레벨이 높을수록 비싼 무기가 상점에 나온다',
    'auto.streak.win': '{n}연승',
    'auto.streak.lose': '{n}연패',
    'auto.lobby': '로비',
    'auto.lobby.note': '생존 {n} / {total} — 마지막까지 남으면 1등. 누르면 그 판을 본다',
    'auto.lobby.me': '나',
    'auto.lobby.hp': '체력 {hp} · Lv.{level}',
    'auto.lobby.out': '{n}등으로 떨어짐',
    'auto.lobby.opp': '이번 상대',
    'auto.bot.hephaestus': '헤파이스토스',
    'auto.bot.eitri': '에이트리',
    'auto.bot.ouyezi': '구야자',
    'auto.bot.vishvakarma': '비슈바카르마',
    'auto.bot.goibniu': '고브니우',
    'auto.scout': '{name}의 판',
    'auto.scout.close': '닫기',
    'auto.enemy.pve': '이번 상대 — 수호자',
    'auto.enemy.pve.note': '모두가 같은 수호자 판({myth})과 싸운다. 이기면 {n}금, 지면 조금 깎인다.',
    'auto.enemy.player': '이번 상대 — {name}',
    'auto.enemy.player.note': '레벨 {level} · 체력 {hp}. 지면 {base} + 살아남은 상대 수만큼 깎인다.',
    'auto.enemy.ghost': '이번 상대 — {name}의 유령',
    'auto.enemy.ghost.note': '남은 수가 홀수라 유령(그 판의 복사본)과 싸운다. 이겨도 주인은 안 깎인다.',
    'auto.board.mid': '가운데',
    'auto.shop.left': ' · 남음 {n}',
    'auto.result.pve': '수호자를 이겼다 — +{n}금',
    'auto.others.me': '▶ 이김',
    'auto.others.them': '▶ 짐',
    'auto.others.draw': '▶ 비김',
    'auto.others.ghost': '유령',
    'auto.others.pve.me': '수호자에게 이김',
    'auto.others.pve.them': '수호자에게 짐',
    'auto.others.pve.draw': '수호자와 비김',
    'auto.end.note': '{n}라운드 · 여섯 중 {place}등',
    'auto.gold': '금',
    'auto.gold.n': '{n}금',
    'auto.hp': '체력',
    'auto.income': '다음 수입 {n}',
    'auto.shop': '상점',
    'auto.shop.note': '값만큼 금을 낸다. 같은 자루 셋이면 별이 오른다. 여섯이 한 더미를 나눠 쓴다 — 남은 장수가 적으면 잘 안 나온다.',
    'auto.reroll': '다시 돌리기 {n}금',
    'auto.buy': '사기',
    'auto.sold': '팔림',
    'auto.bench': '벤치',
    'auto.bench.note': '무기를 누르면 정보가 뜨고, 이어서 판의 칸을 누르면 옮긴다. 상대·로비의 판과 상점 그림도 누르면 정보가 뜬다.',
    'auto.board': '내 판',
    'auto.board.cap': '판 위 {n} / {cap}',
    'auto.board.front': '앞줄',
    'auto.board.back': '뒷줄',
    'auto.enemy': '이번 상대',
    'auto.synergy': '시너지',
    'auto.synergy.off': '{count} / {next}',
    'auto.synergy.on': '{count} — 켜짐',
    'auto.fight': '싸운다',
    'auto.fight.note': '판을 다 놓았으면 싸운다. 싸움은 자동이다.',
    'auto.next': '다음 라운드',
    'auto.result.me': '이겼다',
    'auto.result.them': '졌다 — 체력 −{n}',
    'auto.result.draw': '무승부 — 체력 −{n}',
    'auto.result.beats': '{n}박',
    'auto.result.left': '남은 것 — 나 {me} · 상대 {them}',
    'auto.log': '싸움 기록',
    'auto.log.hit': '{a} → {b} {d}',
    'auto.log.crit': '{a} → {b} {d} 치명타',
    'auto.log.splash': '{a} ⇢ {b} {d} 뒤 칸',
    'auto.log.skillhit': '{a} ✦ {b} {d}',
    'auto.log.skill': '{a} 가 {skill}',
    'auto.log.die': '{b} 쓰러짐',
    'auto.log.revive': '{b} 되살아남 ({hp})',
    'auto.log.curse': '{b} 저주 발현',
    'auto.log.bleed': '{b} 저주 {d}',
    'auto.log.stun': '{b} 멈춤',
    'auto.log.heal': '{b} 회복 +{d}',
    'auto.log.shield': '{b} 보호막 +{d}',
    'auto.log.dot': '{b} 독 {d}',
    'auto.log.selfhurt': '{b} 반동 {d}',
    'auto.log.start': '싸움 시작 — 나 {me} · 상대 {them}',
    'auto.log.end': '끝',
    'auto.log.regen': '{b} 영생 +{d}',
    'auto.log.thorns': '{a} ↩ {b} {d} 되돌림',
    'auto.log.leech': '{b} 비취의 숨 +{d}',
    'auto.log.avenge': '{b} 맹세 — 공격 오름',
    'auto.log.cover': '{a} ⇢ {b} {d} 대신 맞음',
    'auto.play': '싸우는 중',
    'auto.play.left': '나 {me} · 상대 {them}',
    'auto.play.fast': '2배속',
    'auto.play.skip': '건너뛰기',
    'auto.play.again': '다시 보기',
    'auto.won': '1등 — 마지막까지 남았다',
    'auto.lost': '{place}등 — {n}라운드에 체력이 다했다',
    'auto.myths': '이번 판의 신화권',
    'auto.myths.note': '{all}권 중 고른 권만 상점·수호자·맞수에 나온다 — {min}~{max}권. 적을수록 같은 무기가 잘 모이고, 많을수록 판이 넓다. 첫 라운드에 아무것도 사기 전에만 바꿀 수 있다(맞수도 새로 짠다).',
    'auto.myths.locked': '{all}권 중 {n}권만 상점·수호자·맞수에 나온다.',
    'auto.myths.apply': '이대로',
    'auto.myths.count': '{n}권 · {min}~{max}',
    'auto.myths.all': '모든 권 — 신화권을 고르기 전에 시작한 판',
    'auto.new': '새 판',
    'auto.new.note': '지금 판을 버리고 처음부터',
    'auto.autoplan': '대신 두기',
    'auto.autoplan.note': '맡긴 손이 사고 놓는다. 그다음은 네 차례',
    'auto.sell': '팔기 {n}금',
    'auto.pick': '고른 것: {name}',
    'auto.pick.note': '빈 칸이나 다른 무기를 누르면 옮긴다(맞바꾼다). 다시 누르면 내려놓는다.',
    'auto.info.star': '{n}성 — 체력·공격 ×{m}',
    'auto.info.open': '무기 정보',
    'auto.empty': '비었음',
    'auto.star': '★',
    'auto.side.me': '나',
    'auto.side.them': '상대',
    'auto.saved': '판은 이 브라우저에 남는다',
    'auto.why.gold': '금이 모자라다',
    'auto.why.bench': '벤치가 찼다',
    'auto.why.cap': '판 위 수가 레벨만큼이다 — 레벨을 올리면 더 올린다',
    'auto.why.maxlevel': '이미 최대 레벨이다',

    /* 프롬프트 생성기 */
    'prompt.title': '그림 프롬프트',
    'prompt.subtitle': '무기 하나, 화풍 하나, 출력 하나를 고르면 영어 문장이 나온다. 그림 모델에 그대로 넣는다.',
    'prompt.card': '무기',
    'prompt.card.pick': '무기를 고른다',
    'prompt.card.region': '지역',
    'prompt.card.region.n': '{name} · 그림 {n}/{total}',
    'prompt.card.region.skin': '{name} · 스킨 {n}',
    'prompt.card.skinOnly': '스킨 있는 무기만',
    'prompt.card.skinOnly.n': '{n}자루 · 고르면 출력이 스킨으로',
    'prompt.card.noart': '그림 없음',
    'prompt.style': '화풍',
    'prompt.output': '출력',
    'prompt.action': '동작',
    'prompt.casual.index': '일상컷 번호',
    'prompt.scene': '장면 메모 (영어, 선택)',
    'prompt.scene.hint': 'stormy cliff at dusk 처럼 짧게. 비워도 된다.',
    'prompt.identity': '외형',
    'prompt.identity.note': '비우면 자동이다 — 무기와 신화권이 정한다. 고른 것만 문장에 들어가고, 무기마다 따로 기억한다.',
    'prompt.group.set': '{n}개 고름',
    'prompt.design': '설계',
    'prompt.design.note': '기본은 짧다 — 무기·화풍·뼈대 한 문단·규격뿐. 아래는 켜야 붙는 문단이다.',
    'prompt.design.kind': '설계 언어',
    'prompt.extras': '붙일 문단',
    'prompt.posture': '자세',
    'prompt.posture.none': '자동 — 서 있는 위엄 포즈',
    'prompt.figure.pick': '{label} · 그림으로 고르기',
    'prompt.color.pick': '{label} 빠른 선택',
    'prompt.color.rgb': '{label} · RGB 로 고르기',
    'prompt.color.wheel': '{label} 색 상자',
    'prompt.color.says': '프롬프트에',
    'prompt.auto': '자동',
    'prompt.casual': '일상컷 장면',
    'prompt.casual.note': '액션 그림을 첨부해 같은 사람으로 만든다. 외형 표는 안 쓰고 아래 장면 설정만 쓴다.',
    'prompt.casual.category': '일상 갈래',
    'prompt.casual.example': '장면 예시',
    'prompt.casual.pose': '자세',
    'prompt.casual.orient': '방향',
    'prompt.casual.expr': '표정',
    'prompt.casual.outfit': '의상·소품 (영어, 선택)',
    'prompt.casual.scene': '장소·상황 (영어, 선택)',
    'prompt.casual.axes': '세부 강도',
    'prompt.casual.axes.note': '자동이면 안 붙는다. 켜면 그 축의 영어 문장이 장면 설정에 들어간다.',
    'prompt.casual.random': '랜덤',
    'prompt.casual.random.field': '{label} 랜덤',
    'prompt.casual.random.all': '잠기지 않은 항목 전체 랜덤',
    'prompt.casual.lock': '잠금',
    'prompt.casual.locked': '잠김',
    'prompt.casual.lock.field': '{label} 잠금',
    'prompt.casual.tier.basic': '기본',
    'prompt.casual.tier.popular': '대중',
    'prompt.casual.tier.special': '특수',
    'prompt.eye.same': '양쪽 같은 색',
    'prompt.custom': '직접 입력',
    'prompt.result': '프롬프트',
    'prompt.copy': '복사',
    'prompt.copied': '복사했다',
    'prompt.words': '{n}낱말',
    'prompt.file': '저장할 파일 이름',
    'prompt.file.note': '그림 저장소 img/ 에 이 이름으로 올리면 등록은 자동이다. 세로 2:3, 1024×1536, webp.',
    'prompt.awaken.note': '각성은 액션 그림을 첨부해야 한다. 같은 구도에서 무기만 깨어난다.',
    'prompt.skin': '스킨',
    'prompt.skin.note': '기본은 액션 그림을, 각성·저주는 스킨 기본 그림을 첨부한다. 같은 사람·같은 구도에서 바꾼다.',
    'prompt.skin.state': '스킨 상태',
    'prompt.skin.state.base': '기본',
    'prompt.skin.state.awaken': '각성',
    'prompt.skin.state.cursed': '저주',
    'prompt.skin.none': '이 무기엔 스킨이 없다. data/card.json 의 skins 에 먼저 적는다.',
    'prompt.reset': '이 무기의 설정 지우기',
    'prompt.art.have': '액션 그림 있음',
    'prompt.art.none': '액션 그림 아직 없음',

    /* 결투 — 궨트식 1 대 1. 능력·날씨 이름도 여기. 진영 능력 이름·주인 이름은 자료(duel.json · card.wielder) */
    'duel.title': '신기 결투',
    'duel.subtitle': '덱 스물다섯으로 손패 열을 들고, 세 줄에 내려 힘의 합으로 세 라운드 중 둘을 따낸다.',
    'duel.lv.rookie': '신참', 'duel.lv.veteran': '숙련', 'duel.lv.ace': '에이스',
    'duel.lv.note': '신참은 헛발질하고 패스를 모른다. 숙련은 이득을 다 센다. 에이스는 영웅·저주판을 아껴 뒀다 쓴다.',
    'duel.weather.melee': '서리', 'duel.weather.reach': '안개', 'duel.weather.ranged': '비',
    'duel.weather.call': '{w}를 부른다',
    'duel.weather.text': '그 줄 양쪽 비영웅을 1로 센다. 영웅은 그대로. 같은 줄에 또 내면 걷힌다',
    'duel.ability.strike': '타격', 'duel.ability.strike.text': '상대 가장 센 비영웅 −{n}',
    'duel.ability.sweep': '휩쓸기', 'duel.ability.sweep.text': '상대 같은 줄 비영웅 전부 −1',
    'duel.ability.volley': '난사', 'duel.ability.volley.text': '상대 비영웅 무작위 {n}장 −1',
    'duel.ability.execute': '처형', 'duel.ability.execute.text': '상대 가장 약한 비영웅이 5 이하면 파괴, 아니면 −2',
    'duel.ability.seal': '봉인', 'duel.ability.seal.text': '상대가 다음에 내는 비영웅의 능력이 안 터진다',
    'duel.ability.mend': '강화', 'duel.ability.mend.text': '내 같은 줄 가장 약한 비영웅(자신 포함) +{n}',
    'duel.ability.rally': '결집', 'duel.ability.rally.text': '내 같은 줄 나머지 비영웅 전부 +1',
    'duel.ability.shield': '보호막', 'duel.ability.shield.text': '자신과 양옆 카드가 다음 피해 한 번을 막는다',
    'duel.ability.drain': '흡혈', 'duel.ability.drain.text': '상대 가장 센 비영웅 −{n}, 자신 +{n}',
    'duel.variant.base': '기본', 'duel.variant.awaken': '각성판', 'duel.variant.cursed': '저주판', 'duel.variant.weather': '날씨판',
    'duel.variant.awaken.text': '힘 +3',
    'duel.variant.cursed.text': '힘 +5. 상대가 카드를 낼 때마다 −1(바닥 1). 강화·보호막·결속을 못 받는다',
    'duel.hero': '영웅', 'duel.hero.text': '피해·파괴·봉인·강화·보호막·결속을 받지 않는다',
    'duel.bond': '결속', 'duel.bond.text': '같은 주인의 무기가 같은 줄에 둘 이상이면 각각 기본 힘만큼 더한다',
    'duel.power': '힘', 'duel.row': '줄', 'duel.ability': '능력',
    'duel.pick.title': '주 신화권을 고른다',
    'duel.pick.note': '그 권의 기본판 열일곱 장과 다른 권 여덟 장이 시작 덱이다. 주 권의 진영 능력을 한 판에 한 번 쓴다.',
    'duel.pick.go': '이 권으로 시작',
    'duel.lobby': '로비',
    'duel.lobby.main': '주 신화권',
    'duel.lobby.deck': '덱 {n}/{max}',
    'duel.lobby.deck.ok': '출전 가능',
    'duel.lobby.deck.bad': '규칙에 안 맞다 — 덱 짜기에서 고친다',
    'duel.lobby.collection': '컬렉션 {n}/{max}',
    'duel.lobby.build': '덱 짜기',
    'duel.lobby.stats': '전적',
    'duel.lobby.level': '난이도',
    'duel.lobby.bosses': '열한 주인',
    'duel.lobby.bosses.note': '주인은 자기 권 열일곱 장에 이웃 권 여덟 장을 든다. 숙련부터 각성판, 에이스는 저주판·날씨판까지 섞는다.',
    'duel.lobby.conquered': '정복 — 열한 주인을 모두 이겼다',
    'duel.boss.wins': '{n}승',
    'duel.boss.go': '도전',
    'duel.build': '덱 짜기',
    'duel.build.note': '그림을 누르면 능력을 보고, 아래 단추로 넣고 뺀다. 스물다섯 장, 주 권 열다섯 이상, 영웅 넷 이하, 날씨판 셋 이하, 같은 카드는 한 장.',
    'duel.build.rule.count': '{n}/25장',
    'duel.build.rule.main': '주 권 {n}/15',
    'duel.build.rule.hero': '영웅 {n}/4',
    'duel.build.rule.weather': '날씨 {n}/3',
    'duel.build.in': '덱',
    'duel.build.add': '넣기', 'duel.build.remove': '빼기',
    'duel.build.view': '보기', 'duel.build.view.all': '전체', 'duel.build.view.in': '덱에 든 것', 'duel.build.view.out': '안 든 것',
    'duel.build.filter.row': '줄', 'duel.build.filter.myth': '권', 'duel.build.filter.main': '주 권', 'duel.build.filter.other': '나머지',
    'duel.build.rows': '줄별',
    'duel.build.autofill': '자동 채우기',
    'duel.build.autofill.note': '모자라면 규칙을 지키며 센 카드부터 채우고, 넘치면 약한 것부터 뺀다',
    'duel.build.done': '로비로',
    'duel.why.count': '덱은 스물다섯 장이어야 한다',
    'duel.why.main': '주 신화권 카드가 열다섯 장은 있어야 한다',
    'duel.why.hero': '영웅은 넷까지',
    'duel.why.weather': '날씨판은 셋까지',
    'duel.why.dup': '같은 카드가 두 장 들어 있다',
    'duel.why.owned': '안 가진 카드가 덱에 있다',
    'duel.mull.title': '손패를 고른다',
    'duel.mull.note': '두 장까지 눌러 덱 맨 위 카드와 바꾼다. 라운드 사이에 더 뽑지 않는다 — 열 장으로 세 라운드를 나눠 쓴다.',
    'duel.mull.left': '{n}장 더 바꿀 수 있다',
    'duel.mull.go': '시작',
    'duel.first.me': '내가 선공', 'duel.first.foe': '상대가 선공',
    'duel.first.bonus': '선공 +{n}',
    'duel.first.bonus.text': '선공은 1라운드 합에 {n}을 미리 받는다 — 후공이 늘 마지막에 답하는 몫',
    'duel.foe.hand': '손패 {n}', 'duel.foe.grave': '묘지 {n}',
    'duel.faction': '진영 능력',
    'duel.faction.used': '진영 능력 씀',
    'duel.faction.use': '{name} 쓰기',
    'duel.faction.mine': '내 진영 능력', 'duel.faction.foe': '상대의 진영 능력',
    'duel.faction.sheet.use': '쓰기', 'duel.faction.once': '한 판에 한 번. 차례를 쓴다',
    'duel.rules.factions': '진영 능력 열하나',
    'duel.round': '라운드 {n}',
    'duel.lives': '목숨',
    'duel.turn.me': '내 차례', 'duel.turn.foe': '상대 차례',
    'duel.pass': '패스', 'duel.passed': '패스함',
    'duel.play': '내기', 'duel.close': '닫기',
    'duel.hand': '손패 {n}',
    'duel.round.win': '{n}라운드 — 땄다 {me} : {foe}',
    'duel.round.lose': '{n}라운드 — 잃었다 {me} : {foe}',
    'duel.round.draw': '{n}라운드 — 동점, 둘 다 목숨을 잃는다 {me} : {foe}',
    'duel.round.win.short': '{n}라운드 — 땄다', 'duel.round.lose.short': '{n}라운드 — 잃었다', 'duel.round.draw.short': '{n}라운드 — 동점',
    'duel.sealed': '봉인됨', 'duel.shielded': '보호막', 'duel.guard': '호국', 'duel.astra': '아스트라',
    'duel.result.win': '승리', 'duel.result.lose': '패배', 'duel.result.draw': '무승부',
    'duel.result.rounds': '라운드 셋',
    'duel.result.reward': '얻은 카드',
    'duel.result.reward.none': '보상 없음 — 이겨야 카드를 얻는다',
    'duel.result.reward.all': '이 권은 다 모았다',
    'duel.result.reveal': '다음 카드',
    'duel.result.lobby': '로비로', 'duel.result.again': '다시',
    'duel.stats': '전적',
    'duel.stats.line': '{games}판 {win}승 {lose}패 {draw}무 · 연승 {streak} (최고 {best})',
    'duel.stats.byBoss': '주인별', 'duel.stats.byLevel': '난이도별', 'duel.stats.byMain': '주 권별',
    'duel.stats.cell': '{win}/{games}',
    'duel.stats.best': '한 라운드 최고 합 {n}',
    'duel.stats.rounds': '평균 라운드 {n}',
    'duel.stats.cards': '카드별 승률',
    'duel.stats.cards.note': '낸 판 수 순. 다섯 판 미만은 승률 대신 —',
    'duel.stats.card': '{played}판 · {rate}',
    'duel.stats.none': '—',
    'duel.stats.factions': '진영 능력 쓴 수',
    'duel.stats.empty': '아직 판이 없다',
    'duel.stats.close': '닫기',
    'duel.learn': '배우기',
    'duel.rules.title': '규칙 한눈에',
    'duel.rules.1.title': '세 라운드 중 둘',
    'duel.rules.1.text': '덱 스물다섯 장에서 손패 열 장을 뽑고, 그 열 장으로 세 라운드를 치른다 — 라운드 사이에 더 뽑지 않는다. 내 차례엔 카드 한 장을 내거나, 진영 능력을 쓰거나, 패스한다. 둘 다 패스하면 라운드가 끝나고 합이 큰 쪽이 딴다. 동점이면 둘 다 목숨을 잃는다. 목숨은 둘.',
    'duel.rules.2.title': '세 줄과 힘',
    'duel.rules.2.text': '카드는 자기 줄(근접·중거리·원거리)로 간다. 줄마다 힘을 더해 세 줄의 합으로 겨룬다. 능력은 낼 때 한 번 터진다. 영웅(금빛)은 피해도 강화도 받지 않는다. 같은 주인의 무기가 같은 줄에 둘이면 결속으로 기본 힘만큼 더한다.',
    'duel.rules.3.title': '네 가지 판과 날씨',
    'duel.rules.3.text': '한 무기에 기본판·각성판(+3)·저주판(+5, 상대가 낼 때마다 −1)·날씨판이 있다. 날씨판은 힘이 없고, 내면 그 줄에 서리·안개·비가 깔려 양쪽 비영웅을 1로 센다. 같은 줄 날씨판을 또 내면 걷힌다. 패스는 이 라운드를 접고 카드를 아끼는 수다 — 한 라운드를 내주고 다음 두 라운드를 따도 이긴다.',
    'duel.rules.4.title': '진영 능력과 선공',
    'duel.rules.4.text': '주 신화권의 능력을 한 판에 한 번, 차례를 써서 쓴다. 1라운드의 선공은 합에 8을 미리 받는다 — 후공이 늘 마지막에 답하는 몫이다. 이기면 그 주인의 권 카드를 얻는다(첫 승 셋, 재대결 하나).',
    'duel.guide.step': '길잡이 {n}/{total}',
    'duel.guide.skip': '그만 보기',
    'duel.guide.again': '첫 판 길잡이 다시 보기',
    'duel.guide.1': '손패에서 카드를 눌러 보고 "내기"를 누르면 카드의 줄(근접·중거리·원거리)로 간다. 줄 표시 색이 판의 줄과 같다.',
    'duel.guide.2': '냈다. 능력이 있으면 지금 터졌다. 이제 상대가 한 수 둔다 — 번갈아 가며 낸다.',
    'duel.guide.3': '가운데 숫자가 양쪽 합이다. 둘 다 패스하면 라운드가 끝나고 큰 쪽이 딴다. 패스는 이 라운드를 접고 카드를 아끼는 수 — 열 장으로 세 라운드를 나눠 써야 한다.',
    'duel.guide.4': '라운드가 끝났다. 진 쪽이 목숨 하나를 잃고 다음 라운드의 선공이 된다. 판은 비고 손패는 그대로다.',
    'duel.guide.5': '진영 능력 단추는 한 판에 한 번. 차례를 쓰니 때를 고른다.',
    'duel.guide.6': '모서리 표시가 있는 카드는 각성판·저주판·날씨판이다. 날씨판은 그 줄 양쪽 비영웅을 1로 만든다 — 상대가 많이 깐 줄에 쓴다. 목숨 둘을 먼저 잃는 쪽이 진다.',

    /* 그림 */
    'art.none': '그림 없음',
    'art.missing': '아직 안 만든 것',
    'art.count': '{n}장',
    'art.done': '액션 ✓',
    'art.awaken.done': '각성 ✓',
    'art.cursed.done': '저주 ✓',
    'art.states': '기본 · 각성 · 저주',
  };

  var missing = {};
  function W(key, vars) {
    var s = WORDS[key];
    if (s === undefined) {
      /* 조용히 빈칸으로 두면 화면에서만 티가 나고 원인을 못 찾는다 */
      if (!missing[key]) { missing[key] = 1; console.warn('낱말 표에 없는 열쇠: ' + key); }
      return key;
    }
    if (!vars) return s;
    return s.replace(/\{(\w+)\}/g, function (m, k) {
      return vars[k] === undefined ? m : String(vars[k]);
    });
  }

  /* 표를 통째로 갈아 끼울 때(다른 주제로 시험할 때) 쓴다 */
  function load(table) { for (var k in table) WORDS[k] = table[k]; }

  root.AtelierWords = { W: W, load: load, table: WORDS,
    missing: function () { return Object.keys(missing); } };
  root.W = W;   /* 화면에서 짧게 부르라고 */
})(window);
